-- สร้างตาราง users
CREATE TABLE users (
  id INT IDENTITY(1,1) PRIMARY KEY,
  username NVARCHAR(50) UNIQUE NOT NULL,
  password_hash NVARCHAR(255) NOT NULL,
  role NVARCHAR(20) DEFAULT 'user' -- 'user' or 'admin'
);
GO

-- เพิ่มคอลัมน์ user_id ในตาราง bookings
ALTER TABLE bookings ADD user_id INT;
GO

-- ตั้งค่าให้ user_id เป็น Foreign Key เชื่อมกับ users
ALTER TABLE bookings ADD CONSTRAINT FK_Bookings_Users FOREIGN KEY (user_id) REFERENCES users(id);
GO

-- Insert an admin user automatically (password is: admin123)
-- Hash generated by bcryptjs for 'admin123'
INSERT INTO users (username, password_hash, role) 
VALUES ('admin', '$2a$10$wY9PjN.3.W6TjQZ.8Z4R2.T5e0I8F9v0J9X1D6q4T8g2n1s8Q5V5G', 'admin');
GO
