-- สร้างตาราง users
CREATE TABLE users (
  id INT IDENTITY(1,1) PRIMARY KEY,
  username NVARCHAR(50) UNIQUE NOT NULL,
  password_hash NVARCHAR(255) NOT NULL,
  role NVARCHAR(20) DEFAULT 'user' -- 'user' or 'admin'
);
GO

-- เพิ่มคอลัมน์ user_id ในตาราง bookings
ALTER TABLE bookings ADD user_id INT;
GO

-- ตั้งค่าให้ user_id เป็น Foreign Key เชื่อมกับ users
ALTER TABLE bookings ADD CONSTRAINT FK_Bookings_Users FOREIGN KEY (user_id) REFERENCES users(id);
GO

-- Insert an admin user automatically (password is: admin123)
-- Hash generated by bcryptjs for 'admin123'
INSERT INTO users (username, password_hash, role) 
VALUES ('admin', '$2b$10$RlH.eajXwt7s0vtKXowbEuX19hOWL.PBKdGK5MSaVy/81FqrK96HW', 'admin');
GO
